# Generated by Django 3.2.23 on 2024-01-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('site_web', models.URLField()),
                ('num_chambre', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Voyages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('programme', models.TextField()),
                ('info_pratique', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_depart', models.DateField()),
                ('date_arrive', models.DateField()),
                ('destination', models.CharField(max_length=255)),
                ('categories', models.CharField(choices=[('cat1', 'Couples'), ('cat2', ' Familles'), ('cat3', ' Equipes'), ('cat4', 'Haj & Omra ')], max_length=50)),
                ('nombre_de_places', models.PositiveIntegerField()),
                ('nombre_de_places_adultes', models.PositiveIntegerField()),
                ('nombre_de_places_enfants', models.PositiveIntegerField()),
                ('nombre_de_pieces', models.PositiveIntegerField()),
                ('promotions', models.BooleanField(default=False)),
                ('isthebest_destination', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Voyages.hotel')),
                ('photos', models.ManyToManyField(to='Voyages.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voyages.voyages')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='photos',
            field=models.ManyToManyField(to='Voyages.Image'),
        ),
    ]
