# Generated by Django 3.2.23 on 2024-01-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voyages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='repas',
            field=models.CharField(choices=[('repas1', 'Petit déjeuner'), ('repas2', 'Déjeuner'), ('repas3', 'Dîner')], default='repas1', max_length=20),
        ),
    ]
