# Generated by Django 3.2.23 on 2024-01-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voyages', '0002_hotel_repas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyages',
            name='info_pratique',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voyages',
            name='programme',
            field=models.TextField(blank=True),
        ),
    ]
