# Generated by Django 3.2.23 on 2024-01-05 13:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Voyages', '0003_auto_20240105_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyages',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='voyages',
            name='info_pratique',
            field=tinymce.models.HTMLField(verbose_name='Info_pratique'),
        ),
        migrations.AlterField(
            model_name='voyages',
            name='programme',
            field=tinymce.models.HTMLField(verbose_name='Programme'),
        ),
    ]
