# Generated by Django 3.2.23 on 2024-01-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voyages', '0004_auto_20240105_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='siteWEB'),
        ),
    ]
