# Generated by Django 3.2.23 on 2024-01-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voyages', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='repas',
            field=models.CharField(choices=[('repas1', 'Petit déjeuner'), ('repas2', 'Déjeuner'), ('repas3', 'Dîner')], max_length=20),
        ),
    ]
