# Generated by Django 3.2.23 on 2023-12-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0002_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='civilite',
            field=models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame'), ('Mademoiselle', 'Mademoiselle')], max_length=20),
        ),
    ]
