# Generated by Django 3.2.23 on 2024-01-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Voyages', '0004_auto_20240105_1424'),
        ('Reservations', '0003_alter_customuser_civilite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult', models.PositiveIntegerField(default=1)),
                ('enfants', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.customuser')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voyages.voyages')),
            ],
        ),
    ]
