# Generated by Django 3.2.23 on 2024-01-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
