# Generated by Django 3.2.23 on 2024-01-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_cart_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Voyage',
            new_name='voyage',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='Administrator',
        ),
        migrations.AddField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.client'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
