# Generated by Django 3.2.23 on 2024-01-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Voyages', '0006_alter_hotel_repas'),
        ('reservation', '0003_auto_20240115_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.client')),
                ('voyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Voyages.voyages')),
            ],
        ),
    ]
