# Generated by Django 3.2.23 on 2024-01-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_favoris'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
